title: The BabelPic Project
logo: https://pbs.twimg.com/media/EUvjiMCXYAAg1uZ?format=jpg&name=4096x4096
description: A multimodal dataset for non-concrete concept
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
